/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CandleCollection = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
});
export const CandleProduct = IDL.Record({
  'id' : IDL.Nat,
  'collectionId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'priceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCollections' : IDL.Func([], [IDL.Vec(CandleCollection)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [CandleProduct], ['query']),
  'getProductsByCollectionId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CandleProduct)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CandleCollection = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
  });
  const CandleProduct = IDL.Record({
    'id' : IDL.Nat,
    'collectionId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCollections' : IDL.Func([], [IDL.Vec(CandleCollection)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [CandleProduct], ['query']),
    'getProductsByCollectionId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CandleProduct)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };